version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./db:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    ports:
      - "27017:27017"