"""
Django settings for currency_exchange_rates project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from utils import get_db_handle


from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "secret_key"

DEBUG = True

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
    }
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "APP_DIRS": True,
    },
]

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.staticfiles",
    "rest_framework",
    "apps.chart",
]

ROOT_URLCONF = "currency_exchange_rates.urls"

WSGI_APPLICATION = "currency_exchange_rates.wsgi.application"

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

STATIC_URL = "static/"

mongo_client = get_db_handle("localhost", 27017, "root", "mongodb")
